
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.baroservice.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-23T08:53:21.200+09:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "BaroService_SMS",
                      portName = "BaroService_SMSSoap",
                      targetNamespace = "http://ws.baroservice.com/",
                      wsdlLocation = "http://testws.baroservice.com/SMS.asmx?WSDL",
                      endpointInterface = "com.baroservice.ws.BaroServiceSMSSoap")
                      
public class BaroService_SMSSoapImpl implements BaroServiceSMSSoap {

    private static final Logger LOG = Logger.getLogger(BaroService_SMSSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#getSMSSendMessagesByRefKey(java.lang.String certkey, java.lang.String corpNum, java.lang.String refKey)*
     */
    public com.baroservice.ws.ArrayOfSMSMessage getSMSSendMessagesByRefKey(java.lang.String certkey, java.lang.String corpNum, java.lang.String refKey) { 
        LOG.info("Executing operation getSMSSendMessagesByRefKey");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(refKey);
        try {
            com.baroservice.ws.ArrayOfSMSMessage _return = new com.baroservice.ws.ArrayOfSMSMessage();
            java.util.List<com.baroservice.ws.SMSMessage> _returnSMSMessage = new java.util.ArrayList<com.baroservice.ws.SMSMessage>();
            com.baroservice.ws.SMSMessage _returnSMSMessageVal1 = new com.baroservice.ws.SMSMessage();
            _returnSMSMessageVal1.setSendKey("SendKey446626422");
            _returnSMSMessageVal1.setID("ID1686912791");
            _returnSMSMessageVal1.setSenderNum("SenderNum999359393");
            _returnSMSMessageVal1.setReceiverName("ReceiverName1867924170");
            _returnSMSMessageVal1.setReceiverNum("ReceiverNum-1065647810");
            _returnSMSMessageVal1.setMessage("Message70415022");
            _returnSMSMessageVal1.setSendDT("SendDT-488134391");
            _returnSMSMessageVal1.setRefKey("RefKey-1644436466");
            _returnSMSMessageVal1.setSendState(-1538667625);
            _returnSMSMessage.add(_returnSMSMessageVal1);
            _return.getSMSMessage().addAll(_returnSMSMessage);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#changeCorpManager(java.lang.String certkey, java.lang.String corpNum, java.lang.String newManagerID)*
     */
    public int changeCorpManager(java.lang.String certkey, java.lang.String corpNum, java.lang.String newManagerID) { 
        LOG.info("Executing operation changeCorpManager");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(newManagerID);
        try {
            int _return = 2105569540;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#sendMMSMessageFromFTP(java.lang.String certkey, java.lang.String corpNum, java.lang.String senderID, java.lang.String fromNumber, java.lang.String toName, java.lang.String toNumber, java.lang.String txtSubject, java.lang.String txtmessage, java.lang.String imageFileName, java.lang.String sendDT, java.lang.String refKey)*
     */
    public java.lang.String sendMMSMessageFromFTP(java.lang.String certkey, java.lang.String corpNum, java.lang.String senderID, java.lang.String fromNumber, java.lang.String toName, java.lang.String toNumber, java.lang.String txtSubject, java.lang.String txtmessage, java.lang.String imageFileName, java.lang.String sendDT, java.lang.String refKey) { 
        LOG.info("Executing operation sendMMSMessageFromFTP");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(senderID);
        System.out.println(fromNumber);
        System.out.println(toName);
        System.out.println(toNumber);
        System.out.println(txtSubject);
        System.out.println(txtmessage);
        System.out.println(imageFileName);
        System.out.println(sendDT);
        System.out.println(refKey);
        try {
            java.lang.String _return = "_return-469090697";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#sendLMSMessage(java.lang.String certkey, java.lang.String corpNum, java.lang.String senderID, java.lang.String fromNumber, java.lang.String toName, java.lang.String toNumber, java.lang.String subject, java.lang.String contents, java.lang.String sendDT, java.lang.String refKey)*
     */
    public java.lang.String sendLMSMessage(java.lang.String certkey, java.lang.String corpNum, java.lang.String senderID, java.lang.String fromNumber, java.lang.String toName, java.lang.String toNumber, java.lang.String subject, java.lang.String contents, java.lang.String sendDT, java.lang.String refKey) { 
        LOG.info("Executing operation sendLMSMessage");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(senderID);
        System.out.println(fromNumber);
        System.out.println(toName);
        System.out.println(toNumber);
        System.out.println(subject);
        System.out.println(contents);
        System.out.println(sendDT);
        System.out.println(refKey);
        try {
            java.lang.String _return = "_return1871466932";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#checkCorpIsMember(java.lang.String certkey, java.lang.String corpNum, java.lang.String checkCorpNum)*
     */
    public int checkCorpIsMember(java.lang.String certkey, java.lang.String corpNum, java.lang.String checkCorpNum) { 
        LOG.info("Executing operation checkCorpIsMember");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(checkCorpNum);
        try {
            int _return = -894525590;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#cancelReservedSMSMessageByReceiptNum(java.lang.String certkey, java.lang.String corpNum, java.lang.String receiptNum)*
     */
    public int cancelReservedSMSMessageByReceiptNum(java.lang.String certkey, java.lang.String corpNum, java.lang.String receiptNum) { 
        LOG.info("Executing operation cancelReservedSMSMessageByReceiptNum");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(receiptNum);
        try {
            int _return = -1294722267;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#addUserToCorp(java.lang.String certkey, java.lang.String corpNum, java.lang.String memberName, java.lang.String juminNum, java.lang.String id, java.lang.String pwd, java.lang.String grade, java.lang.String tel, java.lang.String hp, java.lang.String email)*
     */
    public int addUserToCorp(java.lang.String certkey, java.lang.String corpNum, java.lang.String memberName, java.lang.String juminNum, java.lang.String id, java.lang.String pwd, java.lang.String grade, java.lang.String tel, java.lang.String hp, java.lang.String email) { 
        LOG.info("Executing operation addUserToCorp");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(memberName);
        System.out.println(juminNum);
        System.out.println(id);
        System.out.println(pwd);
        System.out.println(grade);
        System.out.println(tel);
        System.out.println(hp);
        System.out.println(email);
        try {
            int _return = 1612881118;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#sendMessage(java.lang.String certkey, java.lang.String corpNum, java.lang.String senderID, java.lang.String fromNumber, java.lang.String toName, java.lang.String toNumber, java.lang.String contents, java.lang.String sendDT, java.lang.String refKey)*
     */
    public java.lang.String sendMessage(java.lang.String certkey, java.lang.String corpNum, java.lang.String senderID, java.lang.String fromNumber, java.lang.String toName, java.lang.String toNumber, java.lang.String contents, java.lang.String sendDT, java.lang.String refKey) { 
        LOG.info("Executing operation sendMessage");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(senderID);
        System.out.println(fromNumber);
        System.out.println(toName);
        System.out.println(toNumber);
        System.out.println(contents);
        System.out.println(sendDT);
        System.out.println(refKey);
        try {
            java.lang.String _return = "_return-1041309494";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#updateUserInfo(java.lang.String certkey, java.lang.String corpNum, java.lang.String id, java.lang.String memberName, java.lang.String juminNum, java.lang.String tel, java.lang.String hp, java.lang.String email, java.lang.String grade)*
     */
    public int updateUserInfo(java.lang.String certkey, java.lang.String corpNum, java.lang.String id, java.lang.String memberName, java.lang.String juminNum, java.lang.String tel, java.lang.String hp, java.lang.String email, java.lang.String grade) { 
        LOG.info("Executing operation updateUserInfo");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(id);
        System.out.println(memberName);
        System.out.println(juminNum);
        System.out.println(tel);
        System.out.println(hp);
        System.out.println(email);
        System.out.println(grade);
        try {
            int _return = -1182601204;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#getSMSSendMessages(java.lang.String certkey, java.lang.String corpNum, com.baroservice.ws.ArrayOfString sendKeyList)*
     */
    public com.baroservice.ws.ArrayOfSMSMessage getSMSSendMessages(java.lang.String certkey, java.lang.String corpNum, com.baroservice.ws.ArrayOfString sendKeyList) { 
        LOG.info("Executing operation getSMSSendMessages");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(sendKeyList);
        try {
            com.baroservice.ws.ArrayOfSMSMessage _return = new com.baroservice.ws.ArrayOfSMSMessage();
            java.util.List<com.baroservice.ws.SMSMessage> _returnSMSMessage = new java.util.ArrayList<com.baroservice.ws.SMSMessage>();
            com.baroservice.ws.SMSMessage _returnSMSMessageVal1 = new com.baroservice.ws.SMSMessage();
            _returnSMSMessageVal1.setSendKey("SendKey-299282173");
            _returnSMSMessageVal1.setID("ID-727756942");
            _returnSMSMessageVal1.setSenderNum("SenderNum2097500690");
            _returnSMSMessageVal1.setReceiverName("ReceiverName-342137734");
            _returnSMSMessageVal1.setReceiverNum("ReceiverNum777991268");
            _returnSMSMessageVal1.setMessage("Message-1933030002");
            _returnSMSMessageVal1.setSendDT("SendDT-1540239338");
            _returnSMSMessageVal1.setRefKey("RefKey998997478");
            _returnSMSMessageVal1.setSendState(-358996195);
            _returnSMSMessage.add(_returnSMSMessageVal1);
            _return.getSMSMessage().addAll(_returnSMSMessage);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#getSMSSendMessage(java.lang.String certkey, java.lang.String corpNum, java.lang.String sendKey)*
     */
    public com.baroservice.ws.SMSMessage getSMSSendMessage(java.lang.String certkey, java.lang.String corpNum, java.lang.String sendKey) { 
        LOG.info("Executing operation getSMSSendMessage");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(sendKey);
        try {
            com.baroservice.ws.SMSMessage _return = new com.baroservice.ws.SMSMessage();
            _return.setSendKey("SendKey1288367831");
            _return.setID("ID821443200");
            _return.setSenderNum("SenderNum1620451954");
            _return.setReceiverName("ReceiverName1175124096");
            _return.setReceiverNum("ReceiverNum-816939614");
            _return.setMessage("Message-1293135192");
            _return.setSendDT("SendDT1943375930");
            _return.setRefKey("RefKey636941842");
            _return.setSendState(-472577134);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#getLoginURL(java.lang.String certkey, java.lang.String corpNum, java.lang.String id, java.lang.String pwd)*
     */
    public java.lang.String getLoginURL(java.lang.String certkey, java.lang.String corpNum, java.lang.String id, java.lang.String pwd) { 
        LOG.info("Executing operation getLoginURL");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(id);
        System.out.println(pwd);
        try {
            java.lang.String _return = "_return2101058925";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#getCertificateRegistDate(java.lang.String certkey, java.lang.String corpNum)*
     */
    public java.lang.String getCertificateRegistDate(java.lang.String certkey, java.lang.String corpNum) { 
        LOG.info("Executing operation getCertificateRegistDate");
        System.out.println(certkey);
        System.out.println(corpNum);
        try {
            java.lang.String _return = "_return1002503320";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#checkSMSFromNumber(java.lang.String certkey, java.lang.String corpNum, java.lang.String fromNumber)*
     */
    public int checkSMSFromNumber(java.lang.String certkey, java.lang.String corpNum, java.lang.String fromNumber) { 
        LOG.info("Executing operation checkSMSFromNumber");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(fromNumber);
        try {
            int _return = 828625793;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#registSMSFromNumber(java.lang.String certkey, java.lang.String corpNum, java.lang.String fromNumber)*
     */
    public int registSMSFromNumber(java.lang.String certkey, java.lang.String corpNum, java.lang.String fromNumber) { 
        LOG.info("Executing operation registSMSFromNumber");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(fromNumber);
        try {
            int _return = 708996229;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#checkChargeable(java.lang.String certkey, java.lang.String corpNum, int cType, int docType)*
     */
    public int checkChargeable(java.lang.String certkey, java.lang.String corpNum, int cType, int docType) { 
        LOG.info("Executing operation checkChargeable");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(cType);
        System.out.println(docType);
        try {
            int _return = -961868217;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#getSMSSendMessagesByPaging(java.lang.String certkey, java.lang.String corpNum, java.lang.String fromDate, java.lang.String toDate, int countPerPage, int currentPage)*
     */
    public com.baroservice.ws.PagedSMSMessages getSMSSendMessagesByPaging(java.lang.String certkey, java.lang.String corpNum, java.lang.String fromDate, java.lang.String toDate, int countPerPage, int currentPage) { 
        LOG.info("Executing operation getSMSSendMessagesByPaging");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(fromDate);
        System.out.println(toDate);
        System.out.println(countPerPage);
        System.out.println(currentPage);
        try {
            com.baroservice.ws.PagedSMSMessages _return = new com.baroservice.ws.PagedSMSMessages();
            _return.setCurrentPage(-1042914398);
            _return.setMaxIndex(-528114220);
            _return.setCountPerPage(-1189250127);
            _return.setMaxPageNum(213503900);
            com.baroservice.ws.ArrayOfSMSMessage _returnMessageList = new com.baroservice.ws.ArrayOfSMSMessage();
            java.util.List<com.baroservice.ws.SMSMessage> _returnMessageListSMSMessage = new java.util.ArrayList<com.baroservice.ws.SMSMessage>();
            com.baroservice.ws.SMSMessage _returnMessageListSMSMessageVal1 = new com.baroservice.ws.SMSMessage();
            _returnMessageListSMSMessageVal1.setSendKey("SendKey1301498871");
            _returnMessageListSMSMessageVal1.setID("ID1228680675");
            _returnMessageListSMSMessageVal1.setSenderNum("SenderNum-21098743");
            _returnMessageListSMSMessageVal1.setReceiverName("ReceiverName1426832467");
            _returnMessageListSMSMessageVal1.setReceiverNum("ReceiverNum558858939");
            _returnMessageListSMSMessageVal1.setMessage("Message-657404406");
            _returnMessageListSMSMessageVal1.setSendDT("SendDT333200613");
            _returnMessageListSMSMessageVal1.setRefKey("RefKey2016108199");
            _returnMessageListSMSMessageVal1.setSendState(1564021727);
            _returnMessageListSMSMessage.add(_returnMessageListSMSMessageVal1);
            _returnMessageList.getSMSMessage().addAll(_returnMessageListSMSMessage);
            _return.setMessageList(_returnMessageList);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#ping()*
     */
    public void ping() { 
        LOG.info("Executing operation ping");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#cancelReservedSMSMessage(java.lang.String certkey, java.lang.String corpNum, java.lang.String sendKey)*
     */
    public int cancelReservedSMSMessage(java.lang.String certkey, java.lang.String corpNum, java.lang.String sendKey) { 
        LOG.info("Executing operation cancelReservedSMSMessage");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(sendKey);
        try {
            int _return = 821823257;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#getBalanceCostAmount(java.lang.String certkey, java.lang.String corpNum)*
     */
    public long getBalanceCostAmount(java.lang.String certkey, java.lang.String corpNum) { 
        LOG.info("Executing operation getBalanceCostAmount");
        System.out.println(certkey);
        System.out.println(corpNum);
        try {
            long _return = -7630267780428953539l;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#getBaroBillURL(java.lang.String certkey, java.lang.String corpNum, java.lang.String id, java.lang.String pwd, java.lang.String togo)*
     */
    public java.lang.String getBaroBillURL(java.lang.String certkey, java.lang.String corpNum, java.lang.String id, java.lang.String pwd, java.lang.String togo) { 
        LOG.info("Executing operation getBaroBillURL");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(id);
        System.out.println(pwd);
        System.out.println(togo);
        try {
            java.lang.String _return = "_return-622787931";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#getMessagesByReceiptNum(java.lang.String certkey, java.lang.String corpNum, java.lang.String receiptNum)*
     */
    public com.baroservice.ws.ArrayOfSMSMessage getMessagesByReceiptNum(java.lang.String certkey, java.lang.String corpNum, java.lang.String receiptNum) { 
        LOG.info("Executing operation getMessagesByReceiptNum");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(receiptNum);
        try {
            com.baroservice.ws.ArrayOfSMSMessage _return = new com.baroservice.ws.ArrayOfSMSMessage();
            java.util.List<com.baroservice.ws.SMSMessage> _returnSMSMessage = new java.util.ArrayList<com.baroservice.ws.SMSMessage>();
            com.baroservice.ws.SMSMessage _returnSMSMessageVal1 = new com.baroservice.ws.SMSMessage();
            _returnSMSMessageVal1.setSendKey("SendKey-1572419442");
            _returnSMSMessageVal1.setID("ID897139972");
            _returnSMSMessageVal1.setSenderNum("SenderNum-254290057");
            _returnSMSMessageVal1.setReceiverName("ReceiverName213681763");
            _returnSMSMessageVal1.setReceiverNum("ReceiverNum1868128261");
            _returnSMSMessageVal1.setMessage("Message103485477");
            _returnSMSMessageVal1.setSendDT("SendDT-2051490294");
            _returnSMSMessageVal1.setRefKey("RefKey1492569990");
            _returnSMSMessageVal1.setSendState(117306351);
            _returnSMSMessage.add(_returnSMSMessageVal1);
            _return.getSMSMessage().addAll(_returnSMSMessage);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#getErrString(java.lang.String certkey, int errCode)*
     */
    public java.lang.String getErrString(java.lang.String certkey, int errCode) { 
        LOG.info("Executing operation getErrString");
        System.out.println(certkey);
        System.out.println(errCode);
        try {
            java.lang.String _return = "_return-1545739639";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#sendMessages(java.lang.String certkey, java.lang.String corpNum, java.lang.String senderID, int sendCount, boolean cutToSMS, com.baroservice.ws.ArrayOfXMSMessage messages, java.lang.String sendDT)*
     */
    public java.lang.String sendMessages(java.lang.String certkey, java.lang.String corpNum, java.lang.String senderID, int sendCount, boolean cutToSMS, com.baroservice.ws.ArrayOfXMSMessage messages, java.lang.String sendDT) { 
        LOG.info("Executing operation sendMessages");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(senderID);
        System.out.println(sendCount);
        System.out.println(cutToSMS);
        System.out.println(messages);
        System.out.println(sendDT);
        try {
            java.lang.String _return = "_return-135471923";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#checkCERTIsValid(java.lang.String certkey, java.lang.String corpNum)*
     */
    public int checkCERTIsValid(java.lang.String certkey, java.lang.String corpNum) { 
        LOG.info("Executing operation checkCERTIsValid");
        System.out.println(certkey);
        System.out.println(corpNum);
        try {
            int _return = -1305765671;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#sendSMSMessage(java.lang.String certkey, java.lang.String corpNum, java.lang.String senderID, java.lang.String fromNumber, java.lang.String toName, java.lang.String toNumber, java.lang.String contents, java.lang.String sendDT, java.lang.String refKey)*
     */
    public java.lang.String sendSMSMessage(java.lang.String certkey, java.lang.String corpNum, java.lang.String senderID, java.lang.String fromNumber, java.lang.String toName, java.lang.String toNumber, java.lang.String contents, java.lang.String sendDT, java.lang.String refKey) { 
        LOG.info("Executing operation sendSMSMessage");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(senderID);
        System.out.println(fromNumber);
        System.out.println(toName);
        System.out.println(toNumber);
        System.out.println(contents);
        System.out.println(sendDT);
        System.out.println(refKey);
        try {
            java.lang.String _return = "_return-1933347454";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#getCorpMemberContacts(java.lang.String certkey, java.lang.String corpNum, java.lang.String checkCorpNum)*
     */
    public com.baroservice.ws.ArrayOfContact getCorpMemberContacts(java.lang.String certkey, java.lang.String corpNum, java.lang.String checkCorpNum) { 
        LOG.info("Executing operation getCorpMemberContacts");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(checkCorpNum);
        try {
            com.baroservice.ws.ArrayOfContact _return = new com.baroservice.ws.ArrayOfContact();
            java.util.List<com.baroservice.ws.Contact> _returnContact = new java.util.ArrayList<com.baroservice.ws.Contact>();
            com.baroservice.ws.Contact _returnContactVal1 = new com.baroservice.ws.Contact();
            _returnContactVal1.setID("ID1768341457");
            _returnContactVal1.setContactName("ContactName179095764");
            _returnContactVal1.setGrade("Grade-1956443897");
            _returnContactVal1.setEmail("Email1703493104");
            _returnContactVal1.setTEL("TEL-1151226606");
            _returnContactVal1.setHP("HP376671677");
            _returnContact.add(_returnContactVal1);
            _return.getContact().addAll(_returnContact);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#getSMSFromNumberURL(java.lang.String certkey, java.lang.String corpNum, java.lang.String id, java.lang.String pwd)*
     */
    public java.lang.String getSMSFromNumberURL(java.lang.String certkey, java.lang.String corpNum, java.lang.String id, java.lang.String pwd) { 
        LOG.info("Executing operation getSMSFromNumberURL");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(id);
        System.out.println(pwd);
        try {
            java.lang.String _return = "_return-1557419938";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#getCertificateExpireDate(java.lang.String certkey, java.lang.String corpNum)*
     */
    public java.lang.String getCertificateExpireDate(java.lang.String certkey, java.lang.String corpNum) { 
        LOG.info("Executing operation getCertificateExpireDate");
        System.out.println(certkey);
        System.out.println(corpNum);
        try {
            java.lang.String _return = "_return-1928672549";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#updateUserPWD(java.lang.String certkey, java.lang.String corpNum, java.lang.String id, java.lang.String newPWD)*
     */
    public int updateUserPWD(java.lang.String certkey, java.lang.String corpNum, java.lang.String id, java.lang.String newPWD) { 
        LOG.info("Executing operation updateUserPWD");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(id);
        System.out.println(newPWD);
        try {
            int _return = 1391535685;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#getCashChargeURL(java.lang.String certkey, java.lang.String corpNum, java.lang.String id, java.lang.String pwd)*
     */
    public java.lang.String getCashChargeURL(java.lang.String certkey, java.lang.String corpNum, java.lang.String id, java.lang.String pwd) { 
        LOG.info("Executing operation getCashChargeURL");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(id);
        System.out.println(pwd);
        try {
            java.lang.String _return = "_return-802455223";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#getCertificateRegistURL(java.lang.String certkey, java.lang.String corpNum, java.lang.String id, java.lang.String pwd)*
     */
    public java.lang.String getCertificateRegistURL(java.lang.String certkey, java.lang.String corpNum, java.lang.String id, java.lang.String pwd) { 
        LOG.info("Executing operation getCertificateRegistURL");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(id);
        System.out.println(pwd);
        try {
            java.lang.String _return = "_return2084007637";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#updateCorpInfo(java.lang.String certkey, java.lang.String corpNum, java.lang.String corpName, java.lang.String ceoName, java.lang.String bizType, java.lang.String bizClass, java.lang.String postNum, java.lang.String addr1, java.lang.String addr2)*
     */
    public int updateCorpInfo(java.lang.String certkey, java.lang.String corpNum, java.lang.String corpName, java.lang.String ceoName, java.lang.String bizType, java.lang.String bizClass, java.lang.String postNum, java.lang.String addr1, java.lang.String addr2) { 
        LOG.info("Executing operation updateCorpInfo");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(corpName);
        System.out.println(ceoName);
        System.out.println(bizType);
        System.out.println(bizClass);
        System.out.println(postNum);
        System.out.println(addr1);
        System.out.println(addr2);
        try {
            int _return = 1862684167;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#registCorp(java.lang.String certkey, java.lang.String corpNum, java.lang.String corpName, java.lang.String ceoName, java.lang.String bizType, java.lang.String bizClass, java.lang.String postNum, java.lang.String addr1, java.lang.String addr2, java.lang.String memberName, java.lang.String juminNum, java.lang.String id, java.lang.String pwd, java.lang.String grade, java.lang.String tel, java.lang.String hp, java.lang.String email)*
     */
    public int registCorp(java.lang.String certkey, java.lang.String corpNum, java.lang.String corpName, java.lang.String ceoName, java.lang.String bizType, java.lang.String bizClass, java.lang.String postNum, java.lang.String addr1, java.lang.String addr2, java.lang.String memberName, java.lang.String juminNum, java.lang.String id, java.lang.String pwd, java.lang.String grade, java.lang.String tel, java.lang.String hp, java.lang.String email) { 
        LOG.info("Executing operation registCorp");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(corpName);
        System.out.println(ceoName);
        System.out.println(bizType);
        System.out.println(bizClass);
        System.out.println(postNum);
        System.out.println(addr1);
        System.out.println(addr2);
        System.out.println(memberName);
        System.out.println(juminNum);
        System.out.println(id);
        System.out.println(pwd);
        System.out.println(grade);
        System.out.println(tel);
        System.out.println(hp);
        System.out.println(email);
        try {
            int _return = -365623839;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#getSMSHistoryURL(java.lang.String certkey, java.lang.String corpNum, java.lang.String id, java.lang.String pwd)*
     */
    public java.lang.String getSMSHistoryURL(java.lang.String certkey, java.lang.String corpNum, java.lang.String id, java.lang.String pwd) { 
        LOG.info("Executing operation getSMSHistoryURL");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(id);
        System.out.println(pwd);
        try {
            java.lang.String _return = "_return1327250478";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#sendMMSMessage(java.lang.String certkey, java.lang.String corpNum, java.lang.String senderID, java.lang.String fromNumber, java.lang.String toName, java.lang.String toNumber, java.lang.String txtSubject, java.lang.String txtmessage, byte[] imageFile, java.lang.String sendDT, java.lang.String refKey)*
     */
    public java.lang.String sendMMSMessage(java.lang.String certkey, java.lang.String corpNum, java.lang.String senderID, java.lang.String fromNumber, java.lang.String toName, java.lang.String toNumber, java.lang.String txtSubject, java.lang.String txtmessage, byte[] imageFile, java.lang.String sendDT, java.lang.String refKey) { 
        LOG.info("Executing operation sendMMSMessage");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(senderID);
        System.out.println(fromNumber);
        System.out.println(toName);
        System.out.println(toNumber);
        System.out.println(txtSubject);
        System.out.println(txtmessage);
        System.out.println(imageFile);
        System.out.println(sendDT);
        System.out.println(refKey);
        try {
            java.lang.String _return = "_return-324194736";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#getSMSSendState(java.lang.String certkey, java.lang.String corpNum, java.lang.String sendKey)*
     */
    public int getSMSSendState(java.lang.String certkey, java.lang.String corpNum, java.lang.String sendKey) { 
        LOG.info("Executing operation getSMSSendState");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(sendKey);
        try {
            int _return = 17826896;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#getBalanceCostAmountOfInterOP(java.lang.String certkey)*
     */
    public long getBalanceCostAmountOfInterOP(java.lang.String certkey) { 
        LOG.info("Executing operation getBalanceCostAmountOfInterOP");
        System.out.println(certkey);
        try {
            long _return = -2569933856392164310l;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.baroservice.ws.BaroServiceSMSSoap#getChargeUnitCost(java.lang.String certkey, java.lang.String corpNum, int chargeCode)*
     */
    public int getChargeUnitCost(java.lang.String certkey, java.lang.String corpNum, int chargeCode) { 
        LOG.info("Executing operation getChargeUnitCost");
        System.out.println(certkey);
        System.out.println(corpNum);
        System.out.println(chargeCode);
        try {
            int _return = -1196434143;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
