
package com.baroservice.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-23T08:53:21.030+09:00
 * Generated source version: 3.2.1
 * 
 */
public final class BaroServiceSMSSoap_BaroServiceSMSSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.baroservice.com/", "BaroService_SMS");

    private BaroServiceSMSSoap_BaroServiceSMSSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BaroServiceSMS.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BaroServiceSMS ss = new BaroServiceSMS(wsdlURL, SERVICE_NAME);
        BaroServiceSMSSoap port = ss.getBaroServiceSMSSoap();  
        
        {
        System.out.println("Invoking getSMSSendMessagesByRefKey...");
        java.lang.String _getSMSSendMessagesByRefKey_certkey = "_getSMSSendMessagesByRefKey_certkey1145541134";
        java.lang.String _getSMSSendMessagesByRefKey_corpNum = "_getSMSSendMessagesByRefKey_corpNum-417368917";
        java.lang.String _getSMSSendMessagesByRefKey_refKey = "_getSMSSendMessagesByRefKey_refKey2018714709";
        com.baroservice.ws.ArrayOfSMSMessage _getSMSSendMessagesByRefKey__return = port.getSMSSendMessagesByRefKey(_getSMSSendMessagesByRefKey_certkey, _getSMSSendMessagesByRefKey_corpNum, _getSMSSendMessagesByRefKey_refKey);
        System.out.println("getSMSSendMessagesByRefKey.result=" + _getSMSSendMessagesByRefKey__return);


        }
        {
        System.out.println("Invoking changeCorpManager...");
        java.lang.String _changeCorpManager_certkey = "_changeCorpManager_certkey358966250";
        java.lang.String _changeCorpManager_corpNum = "_changeCorpManager_corpNum-377334779";
        java.lang.String _changeCorpManager_newManagerID = "_changeCorpManager_newManagerID872100668";
        int _changeCorpManager__return = port.changeCorpManager(_changeCorpManager_certkey, _changeCorpManager_corpNum, _changeCorpManager_newManagerID);
        System.out.println("changeCorpManager.result=" + _changeCorpManager__return);


        }
        {
        System.out.println("Invoking sendMMSMessageFromFTP...");
        java.lang.String _sendMMSMessageFromFTP_certkey = "_sendMMSMessageFromFTP_certkey605112483";
        java.lang.String _sendMMSMessageFromFTP_corpNum = "_sendMMSMessageFromFTP_corpNum304613706";
        java.lang.String _sendMMSMessageFromFTP_senderID = "_sendMMSMessageFromFTP_senderID-1689497248";
        java.lang.String _sendMMSMessageFromFTP_fromNumber = "_sendMMSMessageFromFTP_fromNumber86476341";
        java.lang.String _sendMMSMessageFromFTP_toName = "_sendMMSMessageFromFTP_toName-1953609022";
        java.lang.String _sendMMSMessageFromFTP_toNumber = "_sendMMSMessageFromFTP_toNumber641554654";
        java.lang.String _sendMMSMessageFromFTP_txtSubject = "_sendMMSMessageFromFTP_txtSubject774686670";
        java.lang.String _sendMMSMessageFromFTP_txtmessage = "_sendMMSMessageFromFTP_txtmessage553528189";
        java.lang.String _sendMMSMessageFromFTP_imageFileName = "_sendMMSMessageFromFTP_imageFileName2028783725";
        java.lang.String _sendMMSMessageFromFTP_sendDT = "_sendMMSMessageFromFTP_sendDT-1060981734";
        java.lang.String _sendMMSMessageFromFTP_refKey = "_sendMMSMessageFromFTP_refKey-732085535";
        java.lang.String _sendMMSMessageFromFTP__return = port.sendMMSMessageFromFTP(_sendMMSMessageFromFTP_certkey, _sendMMSMessageFromFTP_corpNum, _sendMMSMessageFromFTP_senderID, _sendMMSMessageFromFTP_fromNumber, _sendMMSMessageFromFTP_toName, _sendMMSMessageFromFTP_toNumber, _sendMMSMessageFromFTP_txtSubject, _sendMMSMessageFromFTP_txtmessage, _sendMMSMessageFromFTP_imageFileName, _sendMMSMessageFromFTP_sendDT, _sendMMSMessageFromFTP_refKey);
        System.out.println("sendMMSMessageFromFTP.result=" + _sendMMSMessageFromFTP__return);


        }
        {
        System.out.println("Invoking sendLMSMessage...");
        java.lang.String _sendLMSMessage_certkey = "_sendLMSMessage_certkey1655315624";
        java.lang.String _sendLMSMessage_corpNum = "_sendLMSMessage_corpNum-837534592";
        java.lang.String _sendLMSMessage_senderID = "_sendLMSMessage_senderID-1582051374";
        java.lang.String _sendLMSMessage_fromNumber = "_sendLMSMessage_fromNumber1624321557";
        java.lang.String _sendLMSMessage_toName = "_sendLMSMessage_toName624972465";
        java.lang.String _sendLMSMessage_toNumber = "_sendLMSMessage_toNumber-536868202";
        java.lang.String _sendLMSMessage_subject = "_sendLMSMessage_subject-1304952560";
        java.lang.String _sendLMSMessage_contents = "_sendLMSMessage_contents2123760400";
        java.lang.String _sendLMSMessage_sendDT = "_sendLMSMessage_sendDT-537620250";
        java.lang.String _sendLMSMessage_refKey = "_sendLMSMessage_refKey411115763";
        java.lang.String _sendLMSMessage__return = port.sendLMSMessage(_sendLMSMessage_certkey, _sendLMSMessage_corpNum, _sendLMSMessage_senderID, _sendLMSMessage_fromNumber, _sendLMSMessage_toName, _sendLMSMessage_toNumber, _sendLMSMessage_subject, _sendLMSMessage_contents, _sendLMSMessage_sendDT, _sendLMSMessage_refKey);
        System.out.println("sendLMSMessage.result=" + _sendLMSMessage__return);


        }
        {
        System.out.println("Invoking checkCorpIsMember...");
        java.lang.String _checkCorpIsMember_certkey = "_checkCorpIsMember_certkey-776535257";
        java.lang.String _checkCorpIsMember_corpNum = "_checkCorpIsMember_corpNum-1626236885";
        java.lang.String _checkCorpIsMember_checkCorpNum = "_checkCorpIsMember_checkCorpNum1792764707";
        int _checkCorpIsMember__return = port.checkCorpIsMember(_checkCorpIsMember_certkey, _checkCorpIsMember_corpNum, _checkCorpIsMember_checkCorpNum);
        System.out.println("checkCorpIsMember.result=" + _checkCorpIsMember__return);


        }
        {
        System.out.println("Invoking cancelReservedSMSMessageByReceiptNum...");
        java.lang.String _cancelReservedSMSMessageByReceiptNum_certkey = "_cancelReservedSMSMessageByReceiptNum_certkey1583174820";
        java.lang.String _cancelReservedSMSMessageByReceiptNum_corpNum = "_cancelReservedSMSMessageByReceiptNum_corpNum-2127852793";
        java.lang.String _cancelReservedSMSMessageByReceiptNum_receiptNum = "_cancelReservedSMSMessageByReceiptNum_receiptNum-973581520";
        int _cancelReservedSMSMessageByReceiptNum__return = port.cancelReservedSMSMessageByReceiptNum(_cancelReservedSMSMessageByReceiptNum_certkey, _cancelReservedSMSMessageByReceiptNum_corpNum, _cancelReservedSMSMessageByReceiptNum_receiptNum);
        System.out.println("cancelReservedSMSMessageByReceiptNum.result=" + _cancelReservedSMSMessageByReceiptNum__return);


        }
        {
        System.out.println("Invoking addUserToCorp...");
        java.lang.String _addUserToCorp_certkey = "_addUserToCorp_certkey-854983870";
        java.lang.String _addUserToCorp_corpNum = "_addUserToCorp_corpNum885382116";
        java.lang.String _addUserToCorp_memberName = "_addUserToCorp_memberName1186675667";
        java.lang.String _addUserToCorp_juminNum = "_addUserToCorp_juminNum1194148965";
        java.lang.String _addUserToCorp_id = "_addUserToCorp_id-856229423";
        java.lang.String _addUserToCorp_pwd = "_addUserToCorp_pwd1322289858";
        java.lang.String _addUserToCorp_grade = "_addUserToCorp_grade-2080321360";
        java.lang.String _addUserToCorp_tel = "_addUserToCorp_tel224030153";
        java.lang.String _addUserToCorp_hp = "_addUserToCorp_hp2047356422";
        java.lang.String _addUserToCorp_email = "_addUserToCorp_email3519999";
        int _addUserToCorp__return = port.addUserToCorp(_addUserToCorp_certkey, _addUserToCorp_corpNum, _addUserToCorp_memberName, _addUserToCorp_juminNum, _addUserToCorp_id, _addUserToCorp_pwd, _addUserToCorp_grade, _addUserToCorp_tel, _addUserToCorp_hp, _addUserToCorp_email);
        System.out.println("addUserToCorp.result=" + _addUserToCorp__return);


        }
        {
        System.out.println("Invoking sendMessage...");
        java.lang.String _sendMessage_certkey = "_sendMessage_certkey-219246624";
        java.lang.String _sendMessage_corpNum = "_sendMessage_corpNum-1473267043";
        java.lang.String _sendMessage_senderID = "_sendMessage_senderID1970432239";
        java.lang.String _sendMessage_fromNumber = "_sendMessage_fromNumber743366716";
        java.lang.String _sendMessage_toName = "_sendMessage_toName217864974";
        java.lang.String _sendMessage_toNumber = "_sendMessage_toNumber-2095355099";
        java.lang.String _sendMessage_contents = "_sendMessage_contents1078034413";
        java.lang.String _sendMessage_sendDT = "_sendMessage_sendDT628135252";
        java.lang.String _sendMessage_refKey = "_sendMessage_refKey-675942166";
        java.lang.String _sendMessage__return = port.sendMessage(_sendMessage_certkey, _sendMessage_corpNum, _sendMessage_senderID, _sendMessage_fromNumber, _sendMessage_toName, _sendMessage_toNumber, _sendMessage_contents, _sendMessage_sendDT, _sendMessage_refKey);
        System.out.println("sendMessage.result=" + _sendMessage__return);


        }
        {
        System.out.println("Invoking updateUserInfo...");
        java.lang.String _updateUserInfo_certkey = "_updateUserInfo_certkey-1724450641";
        java.lang.String _updateUserInfo_corpNum = "_updateUserInfo_corpNum1472264802";
        java.lang.String _updateUserInfo_id = "_updateUserInfo_id192681990";
        java.lang.String _updateUserInfo_memberName = "_updateUserInfo_memberName1442001912";
        java.lang.String _updateUserInfo_juminNum = "_updateUserInfo_juminNum1565504980";
        java.lang.String _updateUserInfo_tel = "_updateUserInfo_tel2010474153";
        java.lang.String _updateUserInfo_hp = "_updateUserInfo_hp925615575";
        java.lang.String _updateUserInfo_email = "_updateUserInfo_email-1488090459";
        java.lang.String _updateUserInfo_grade = "_updateUserInfo_grade2107813629";
        int _updateUserInfo__return = port.updateUserInfo(_updateUserInfo_certkey, _updateUserInfo_corpNum, _updateUserInfo_id, _updateUserInfo_memberName, _updateUserInfo_juminNum, _updateUserInfo_tel, _updateUserInfo_hp, _updateUserInfo_email, _updateUserInfo_grade);
        System.out.println("updateUserInfo.result=" + _updateUserInfo__return);


        }
        {
        System.out.println("Invoking getSMSSendMessages...");
        java.lang.String _getSMSSendMessages_certkey = "_getSMSSendMessages_certkey794921542";
        java.lang.String _getSMSSendMessages_corpNum = "_getSMSSendMessages_corpNum-630762186";
        com.baroservice.ws.ArrayOfString _getSMSSendMessages_sendKeyList = new com.baroservice.ws.ArrayOfString();
        java.util.List<java.lang.String> _getSMSSendMessages_sendKeyListString = new java.util.ArrayList<java.lang.String>();
        java.lang.String _getSMSSendMessages_sendKeyListStringVal1 = "_getSMSSendMessages_sendKeyListStringVal2097327259";
        _getSMSSendMessages_sendKeyListString.add(_getSMSSendMessages_sendKeyListStringVal1);
        _getSMSSendMessages_sendKeyList.getString().addAll(_getSMSSendMessages_sendKeyListString);
        com.baroservice.ws.ArrayOfSMSMessage _getSMSSendMessages__return = port.getSMSSendMessages(_getSMSSendMessages_certkey, _getSMSSendMessages_corpNum, _getSMSSendMessages_sendKeyList);
        System.out.println("getSMSSendMessages.result=" + _getSMSSendMessages__return);


        }
        {
        System.out.println("Invoking getSMSSendMessage...");
        java.lang.String _getSMSSendMessage_certkey = "_getSMSSendMessage_certkey-1906864344";
        java.lang.String _getSMSSendMessage_corpNum = "_getSMSSendMessage_corpNum-1127095970";
        java.lang.String _getSMSSendMessage_sendKey = "_getSMSSendMessage_sendKey1394299360";
        com.baroservice.ws.SMSMessage _getSMSSendMessage__return = port.getSMSSendMessage(_getSMSSendMessage_certkey, _getSMSSendMessage_corpNum, _getSMSSendMessage_sendKey);
        System.out.println("getSMSSendMessage.result=" + _getSMSSendMessage__return);


        }
        {
        System.out.println("Invoking getLoginURL...");
        java.lang.String _getLoginURL_certkey = "_getLoginURL_certkey1571189077";
        java.lang.String _getLoginURL_corpNum = "_getLoginURL_corpNum1681820908";
        java.lang.String _getLoginURL_id = "_getLoginURL_id1268523369";
        java.lang.String _getLoginURL_pwd = "_getLoginURL_pwd2145483654";
        java.lang.String _getLoginURL__return = port.getLoginURL(_getLoginURL_certkey, _getLoginURL_corpNum, _getLoginURL_id, _getLoginURL_pwd);
        System.out.println("getLoginURL.result=" + _getLoginURL__return);


        }
        {
        System.out.println("Invoking getCertificateRegistDate...");
        java.lang.String _getCertificateRegistDate_certkey = "_getCertificateRegistDate_certkey1829401589";
        java.lang.String _getCertificateRegistDate_corpNum = "_getCertificateRegistDate_corpNum789685178";
        java.lang.String _getCertificateRegistDate__return = port.getCertificateRegistDate(_getCertificateRegistDate_certkey, _getCertificateRegistDate_corpNum);
        System.out.println("getCertificateRegistDate.result=" + _getCertificateRegistDate__return);


        }
        {
        System.out.println("Invoking checkSMSFromNumber...");
        java.lang.String _checkSMSFromNumber_certkey = "_checkSMSFromNumber_certkey2116530981";
        java.lang.String _checkSMSFromNumber_corpNum = "_checkSMSFromNumber_corpNum1518201516";
        java.lang.String _checkSMSFromNumber_fromNumber = "_checkSMSFromNumber_fromNumber1557897301";
        int _checkSMSFromNumber__return = port.checkSMSFromNumber(_checkSMSFromNumber_certkey, _checkSMSFromNumber_corpNum, _checkSMSFromNumber_fromNumber);
        System.out.println("checkSMSFromNumber.result=" + _checkSMSFromNumber__return);


        }
        {
        System.out.println("Invoking registSMSFromNumber...");
        java.lang.String _registSMSFromNumber_certkey = "_registSMSFromNumber_certkey-541483675";
        java.lang.String _registSMSFromNumber_corpNum = "_registSMSFromNumber_corpNum1030707149";
        java.lang.String _registSMSFromNumber_fromNumber = "_registSMSFromNumber_fromNumber-32563245";
        int _registSMSFromNumber__return = port.registSMSFromNumber(_registSMSFromNumber_certkey, _registSMSFromNumber_corpNum, _registSMSFromNumber_fromNumber);
        System.out.println("registSMSFromNumber.result=" + _registSMSFromNumber__return);


        }
        {
        System.out.println("Invoking checkChargeable...");
        java.lang.String _checkChargeable_certkey = "_checkChargeable_certkey1776483675";
        java.lang.String _checkChargeable_corpNum = "_checkChargeable_corpNum-1877233693";
        int _checkChargeable_cType = 268135818;
        int _checkChargeable_docType = 1007509722;
        int _checkChargeable__return = port.checkChargeable(_checkChargeable_certkey, _checkChargeable_corpNum, _checkChargeable_cType, _checkChargeable_docType);
        System.out.println("checkChargeable.result=" + _checkChargeable__return);


        }
        {
        System.out.println("Invoking getSMSSendMessagesByPaging...");
        java.lang.String _getSMSSendMessagesByPaging_certkey = "_getSMSSendMessagesByPaging_certkey181946513";
        java.lang.String _getSMSSendMessagesByPaging_corpNum = "_getSMSSendMessagesByPaging_corpNum-285428907";
        java.lang.String _getSMSSendMessagesByPaging_fromDate = "_getSMSSendMessagesByPaging_fromDate1876395818";
        java.lang.String _getSMSSendMessagesByPaging_toDate = "_getSMSSendMessagesByPaging_toDate-837285728";
        int _getSMSSendMessagesByPaging_countPerPage = 1032468212;
        int _getSMSSendMessagesByPaging_currentPage = -539806652;
        com.baroservice.ws.PagedSMSMessages _getSMSSendMessagesByPaging__return = port.getSMSSendMessagesByPaging(_getSMSSendMessagesByPaging_certkey, _getSMSSendMessagesByPaging_corpNum, _getSMSSendMessagesByPaging_fromDate, _getSMSSendMessagesByPaging_toDate, _getSMSSendMessagesByPaging_countPerPage, _getSMSSendMessagesByPaging_currentPage);
        System.out.println("getSMSSendMessagesByPaging.result=" + _getSMSSendMessagesByPaging__return);


        }
        {
        System.out.println("Invoking ping...");
        port.ping();


        }
        {
        System.out.println("Invoking cancelReservedSMSMessage...");
        java.lang.String _cancelReservedSMSMessage_certkey = "_cancelReservedSMSMessage_certkey1646086927";
        java.lang.String _cancelReservedSMSMessage_corpNum = "_cancelReservedSMSMessage_corpNum-1051349778";
        java.lang.String _cancelReservedSMSMessage_sendKey = "_cancelReservedSMSMessage_sendKey1191800587";
        int _cancelReservedSMSMessage__return = port.cancelReservedSMSMessage(_cancelReservedSMSMessage_certkey, _cancelReservedSMSMessage_corpNum, _cancelReservedSMSMessage_sendKey);
        System.out.println("cancelReservedSMSMessage.result=" + _cancelReservedSMSMessage__return);


        }
        {
        System.out.println("Invoking getBalanceCostAmount...");
        java.lang.String _getBalanceCostAmount_certkey = "_getBalanceCostAmount_certkey-869145043";
        java.lang.String _getBalanceCostAmount_corpNum = "_getBalanceCostAmount_corpNum-841364119";
        long _getBalanceCostAmount__return = port.getBalanceCostAmount(_getBalanceCostAmount_certkey, _getBalanceCostAmount_corpNum);
        System.out.println("getBalanceCostAmount.result=" + _getBalanceCostAmount__return);


        }
        {
        System.out.println("Invoking getBaroBillURL...");
        java.lang.String _getBaroBillURL_certkey = "_getBaroBillURL_certkey-988397932";
        java.lang.String _getBaroBillURL_corpNum = "_getBaroBillURL_corpNum-1329557445";
        java.lang.String _getBaroBillURL_id = "_getBaroBillURL_id-1761068481";
        java.lang.String _getBaroBillURL_pwd = "_getBaroBillURL_pwd179427751";
        java.lang.String _getBaroBillURL_togo = "_getBaroBillURL_togo-810252335";
        java.lang.String _getBaroBillURL__return = port.getBaroBillURL(_getBaroBillURL_certkey, _getBaroBillURL_corpNum, _getBaroBillURL_id, _getBaroBillURL_pwd, _getBaroBillURL_togo);
        System.out.println("getBaroBillURL.result=" + _getBaroBillURL__return);


        }
        {
        System.out.println("Invoking getMessagesByReceiptNum...");
        java.lang.String _getMessagesByReceiptNum_certkey = "_getMessagesByReceiptNum_certkey1345641305";
        java.lang.String _getMessagesByReceiptNum_corpNum = "_getMessagesByReceiptNum_corpNum-1047585182";
        java.lang.String _getMessagesByReceiptNum_receiptNum = "_getMessagesByReceiptNum_receiptNum-587407574";
        com.baroservice.ws.ArrayOfSMSMessage _getMessagesByReceiptNum__return = port.getMessagesByReceiptNum(_getMessagesByReceiptNum_certkey, _getMessagesByReceiptNum_corpNum, _getMessagesByReceiptNum_receiptNum);
        System.out.println("getMessagesByReceiptNum.result=" + _getMessagesByReceiptNum__return);


        }
        {
        System.out.println("Invoking getErrString...");
        java.lang.String _getErrString_certkey = "_getErrString_certkey-190403337";
        int _getErrString_errCode = 248533120;
        java.lang.String _getErrString__return = port.getErrString(_getErrString_certkey, _getErrString_errCode);
        System.out.println("getErrString.result=" + _getErrString__return);


        }
        {
        System.out.println("Invoking sendMessages...");
        java.lang.String _sendMessages_certkey = "_sendMessages_certkey1788094587";
        java.lang.String _sendMessages_corpNum = "_sendMessages_corpNum-1940556485";
        java.lang.String _sendMessages_senderID = "_sendMessages_senderID327390031";
        int _sendMessages_sendCount = -607168987;
        boolean _sendMessages_cutToSMS = false;
        com.baroservice.ws.ArrayOfXMSMessage _sendMessages_messages = new com.baroservice.ws.ArrayOfXMSMessage();
        java.util.List<com.baroservice.ws.XMSMessage> _sendMessages_messagesXMSMessage = new java.util.ArrayList<com.baroservice.ws.XMSMessage>();
        com.baroservice.ws.XMSMessage _sendMessages_messagesXMSMessageVal1 = new com.baroservice.ws.XMSMessage();
        _sendMessages_messagesXMSMessageVal1.setSenderNum("SenderNum504998463");
        _sendMessages_messagesXMSMessageVal1.setReceiverName("ReceiverName599609913");
        _sendMessages_messagesXMSMessageVal1.setReceiverNum("ReceiverNum-243712664");
        _sendMessages_messagesXMSMessageVal1.setMessage("Message1413916516");
        _sendMessages_messagesXMSMessageVal1.setRefKey("RefKey-1639673303");
        _sendMessages_messagesXMSMessage.add(_sendMessages_messagesXMSMessageVal1);
        _sendMessages_messages.getXMSMessage().addAll(_sendMessages_messagesXMSMessage);
        java.lang.String _sendMessages_sendDT = "_sendMessages_sendDT-1708191080";
        java.lang.String _sendMessages__return = port.sendMessages(_sendMessages_certkey, _sendMessages_corpNum, _sendMessages_senderID, _sendMessages_sendCount, _sendMessages_cutToSMS, _sendMessages_messages, _sendMessages_sendDT);
        System.out.println("sendMessages.result=" + _sendMessages__return);


        }
        {
        System.out.println("Invoking checkCERTIsValid...");
        java.lang.String _checkCERTIsValid_certkey = "_checkCERTIsValid_certkey829175724";
        java.lang.String _checkCERTIsValid_corpNum = "_checkCERTIsValid_corpNum-440856371";
        int _checkCERTIsValid__return = port.checkCERTIsValid(_checkCERTIsValid_certkey, _checkCERTIsValid_corpNum);
        System.out.println("checkCERTIsValid.result=" + _checkCERTIsValid__return);


        }
        {
        System.out.println("Invoking sendSMSMessage...");
        java.lang.String _sendSMSMessage_certkey = "_sendSMSMessage_certkey430819375";
        java.lang.String _sendSMSMessage_corpNum = "_sendSMSMessage_corpNum-1365311380";
        java.lang.String _sendSMSMessage_senderID = "_sendSMSMessage_senderID2000327017";
        java.lang.String _sendSMSMessage_fromNumber = "_sendSMSMessage_fromNumber1641715112";
        java.lang.String _sendSMSMessage_toName = "_sendSMSMessage_toName-1001203777";
        java.lang.String _sendSMSMessage_toNumber = "_sendSMSMessage_toNumber-163892545";
        java.lang.String _sendSMSMessage_contents = "_sendSMSMessage_contents371213888";
        java.lang.String _sendSMSMessage_sendDT = "_sendSMSMessage_sendDT689865089";
        java.lang.String _sendSMSMessage_refKey = "_sendSMSMessage_refKey941211828";
        java.lang.String _sendSMSMessage__return = port.sendSMSMessage(_sendSMSMessage_certkey, _sendSMSMessage_corpNum, _sendSMSMessage_senderID, _sendSMSMessage_fromNumber, _sendSMSMessage_toName, _sendSMSMessage_toNumber, _sendSMSMessage_contents, _sendSMSMessage_sendDT, _sendSMSMessage_refKey);
        System.out.println("sendSMSMessage.result=" + _sendSMSMessage__return);


        }
        {
        System.out.println("Invoking getCorpMemberContacts...");
        java.lang.String _getCorpMemberContacts_certkey = "_getCorpMemberContacts_certkey-685593147";
        java.lang.String _getCorpMemberContacts_corpNum = "_getCorpMemberContacts_corpNum1400193615";
        java.lang.String _getCorpMemberContacts_checkCorpNum = "_getCorpMemberContacts_checkCorpNum1558514875";
        com.baroservice.ws.ArrayOfContact _getCorpMemberContacts__return = port.getCorpMemberContacts(_getCorpMemberContacts_certkey, _getCorpMemberContacts_corpNum, _getCorpMemberContacts_checkCorpNum);
        System.out.println("getCorpMemberContacts.result=" + _getCorpMemberContacts__return);


        }
        {
        System.out.println("Invoking getSMSFromNumberURL...");
        java.lang.String _getSMSFromNumberURL_certkey = "_getSMSFromNumberURL_certkey-1279587644";
        java.lang.String _getSMSFromNumberURL_corpNum = "_getSMSFromNumberURL_corpNum645522238";
        java.lang.String _getSMSFromNumberURL_id = "_getSMSFromNumberURL_id888267974";
        java.lang.String _getSMSFromNumberURL_pwd = "_getSMSFromNumberURL_pwd-127406705";
        java.lang.String _getSMSFromNumberURL__return = port.getSMSFromNumberURL(_getSMSFromNumberURL_certkey, _getSMSFromNumberURL_corpNum, _getSMSFromNumberURL_id, _getSMSFromNumberURL_pwd);
        System.out.println("getSMSFromNumberURL.result=" + _getSMSFromNumberURL__return);


        }
        {
        System.out.println("Invoking getCertificateExpireDate...");
        java.lang.String _getCertificateExpireDate_certkey = "_getCertificateExpireDate_certkey1769282621";
        java.lang.String _getCertificateExpireDate_corpNum = "_getCertificateExpireDate_corpNum-795060961";
        java.lang.String _getCertificateExpireDate__return = port.getCertificateExpireDate(_getCertificateExpireDate_certkey, _getCertificateExpireDate_corpNum);
        System.out.println("getCertificateExpireDate.result=" + _getCertificateExpireDate__return);


        }
        {
        System.out.println("Invoking updateUserPWD...");
        java.lang.String _updateUserPWD_certkey = "_updateUserPWD_certkey-585066566";
        java.lang.String _updateUserPWD_corpNum = "_updateUserPWD_corpNum183530836";
        java.lang.String _updateUserPWD_id = "_updateUserPWD_id-653146128";
        java.lang.String _updateUserPWD_newPWD = "_updateUserPWD_newPWD-1611448720";
        int _updateUserPWD__return = port.updateUserPWD(_updateUserPWD_certkey, _updateUserPWD_corpNum, _updateUserPWD_id, _updateUserPWD_newPWD);
        System.out.println("updateUserPWD.result=" + _updateUserPWD__return);


        }
        {
        System.out.println("Invoking getCashChargeURL...");
        java.lang.String _getCashChargeURL_certkey = "_getCashChargeURL_certkey2058391865";
        java.lang.String _getCashChargeURL_corpNum = "_getCashChargeURL_corpNum1308343808";
        java.lang.String _getCashChargeURL_id = "_getCashChargeURL_id-1411234195";
        java.lang.String _getCashChargeURL_pwd = "_getCashChargeURL_pwd487810679";
        java.lang.String _getCashChargeURL__return = port.getCashChargeURL(_getCashChargeURL_certkey, _getCashChargeURL_corpNum, _getCashChargeURL_id, _getCashChargeURL_pwd);
        System.out.println("getCashChargeURL.result=" + _getCashChargeURL__return);


        }
        {
        System.out.println("Invoking getCertificateRegistURL...");
        java.lang.String _getCertificateRegistURL_certkey = "_getCertificateRegistURL_certkey1577783709";
        java.lang.String _getCertificateRegistURL_corpNum = "_getCertificateRegistURL_corpNum-1187664914";
        java.lang.String _getCertificateRegistURL_id = "_getCertificateRegistURL_id-756740496";
        java.lang.String _getCertificateRegistURL_pwd = "_getCertificateRegistURL_pwd-2008907242";
        java.lang.String _getCertificateRegistURL__return = port.getCertificateRegistURL(_getCertificateRegistURL_certkey, _getCertificateRegistURL_corpNum, _getCertificateRegistURL_id, _getCertificateRegistURL_pwd);
        System.out.println("getCertificateRegistURL.result=" + _getCertificateRegistURL__return);


        }
        {
        System.out.println("Invoking updateCorpInfo...");
        java.lang.String _updateCorpInfo_certkey = "_updateCorpInfo_certkey-1932676315";
        java.lang.String _updateCorpInfo_corpNum = "_updateCorpInfo_corpNum-444872735";
        java.lang.String _updateCorpInfo_corpName = "_updateCorpInfo_corpName-1299431270";
        java.lang.String _updateCorpInfo_ceoName = "_updateCorpInfo_ceoName598132593";
        java.lang.String _updateCorpInfo_bizType = "_updateCorpInfo_bizType1776393921";
        java.lang.String _updateCorpInfo_bizClass = "_updateCorpInfo_bizClass61158728";
        java.lang.String _updateCorpInfo_postNum = "_updateCorpInfo_postNum-606954909";
        java.lang.String _updateCorpInfo_addr1 = "_updateCorpInfo_addr11684641747";
        java.lang.String _updateCorpInfo_addr2 = "_updateCorpInfo_addr2470858284";
        int _updateCorpInfo__return = port.updateCorpInfo(_updateCorpInfo_certkey, _updateCorpInfo_corpNum, _updateCorpInfo_corpName, _updateCorpInfo_ceoName, _updateCorpInfo_bizType, _updateCorpInfo_bizClass, _updateCorpInfo_postNum, _updateCorpInfo_addr1, _updateCorpInfo_addr2);
        System.out.println("updateCorpInfo.result=" + _updateCorpInfo__return);


        }
        {
        System.out.println("Invoking registCorp...");
        java.lang.String _registCorp_certkey = "_registCorp_certkey1675446467";
        java.lang.String _registCorp_corpNum = "_registCorp_corpNum1253581903";
        java.lang.String _registCorp_corpName = "_registCorp_corpName1111516114";
        java.lang.String _registCorp_ceoName = "_registCorp_ceoName-243850432";
        java.lang.String _registCorp_bizType = "_registCorp_bizType1261601509";
        java.lang.String _registCorp_bizClass = "_registCorp_bizClass-299954337";
        java.lang.String _registCorp_postNum = "_registCorp_postNum1046293936";
        java.lang.String _registCorp_addr1 = "_registCorp_addr11430293637";
        java.lang.String _registCorp_addr2 = "_registCorp_addr21725166395";
        java.lang.String _registCorp_memberName = "_registCorp_memberName-1617660470";
        java.lang.String _registCorp_juminNum = "_registCorp_juminNum-17150460";
        java.lang.String _registCorp_id = "_registCorp_id470175498";
        java.lang.String _registCorp_pwd = "_registCorp_pwd462636941";
        java.lang.String _registCorp_grade = "_registCorp_grade-501746964";
        java.lang.String _registCorp_tel = "_registCorp_tel-1983160680";
        java.lang.String _registCorp_hp = "_registCorp_hp454837624";
        java.lang.String _registCorp_email = "_registCorp_email1289882467";
        int _registCorp__return = port.registCorp(_registCorp_certkey, _registCorp_corpNum, _registCorp_corpName, _registCorp_ceoName, _registCorp_bizType, _registCorp_bizClass, _registCorp_postNum, _registCorp_addr1, _registCorp_addr2, _registCorp_memberName, _registCorp_juminNum, _registCorp_id, _registCorp_pwd, _registCorp_grade, _registCorp_tel, _registCorp_hp, _registCorp_email);
        System.out.println("registCorp.result=" + _registCorp__return);


        }
        {
        System.out.println("Invoking getSMSHistoryURL...");
        java.lang.String _getSMSHistoryURL_certkey = "_getSMSHistoryURL_certkey682641022";
        java.lang.String _getSMSHistoryURL_corpNum = "_getSMSHistoryURL_corpNum1742172053";
        java.lang.String _getSMSHistoryURL_id = "_getSMSHistoryURL_id-1385708445";
        java.lang.String _getSMSHistoryURL_pwd = "_getSMSHistoryURL_pwd-723199030";
        java.lang.String _getSMSHistoryURL__return = port.getSMSHistoryURL(_getSMSHistoryURL_certkey, _getSMSHistoryURL_corpNum, _getSMSHistoryURL_id, _getSMSHistoryURL_pwd);
        System.out.println("getSMSHistoryURL.result=" + _getSMSHistoryURL__return);


        }
        {
        System.out.println("Invoking sendMMSMessage...");
        java.lang.String _sendMMSMessage_certkey = "_sendMMSMessage_certkey-406161657";
        java.lang.String _sendMMSMessage_corpNum = "_sendMMSMessage_corpNum-555816227";
        java.lang.String _sendMMSMessage_senderID = "_sendMMSMessage_senderID104678371";
        java.lang.String _sendMMSMessage_fromNumber = "_sendMMSMessage_fromNumber-1616932009";
        java.lang.String _sendMMSMessage_toName = "_sendMMSMessage_toName-498849902";
        java.lang.String _sendMMSMessage_toNumber = "_sendMMSMessage_toNumber565299640";
        java.lang.String _sendMMSMessage_txtSubject = "_sendMMSMessage_txtSubject-445215133";
        java.lang.String _sendMMSMessage_txtmessage = "_sendMMSMessage_txtmessage1240052332";
        byte[] _sendMMSMessage_imageFile = new byte[] {};
        java.lang.String _sendMMSMessage_sendDT = "_sendMMSMessage_sendDT-2082925407";
        java.lang.String _sendMMSMessage_refKey = "_sendMMSMessage_refKey-134152015";
        java.lang.String _sendMMSMessage__return = port.sendMMSMessage(_sendMMSMessage_certkey, _sendMMSMessage_corpNum, _sendMMSMessage_senderID, _sendMMSMessage_fromNumber, _sendMMSMessage_toName, _sendMMSMessage_toNumber, _sendMMSMessage_txtSubject, _sendMMSMessage_txtmessage, _sendMMSMessage_imageFile, _sendMMSMessage_sendDT, _sendMMSMessage_refKey);
        System.out.println("sendMMSMessage.result=" + _sendMMSMessage__return);


        }
        {
        System.out.println("Invoking getSMSSendState...");
        java.lang.String _getSMSSendState_certkey = "_getSMSSendState_certkey1622968504";
        java.lang.String _getSMSSendState_corpNum = "_getSMSSendState_corpNum-368408647";
        java.lang.String _getSMSSendState_sendKey = "_getSMSSendState_sendKey1773595745";
        int _getSMSSendState__return = port.getSMSSendState(_getSMSSendState_certkey, _getSMSSendState_corpNum, _getSMSSendState_sendKey);
        System.out.println("getSMSSendState.result=" + _getSMSSendState__return);


        }
        {
        System.out.println("Invoking getBalanceCostAmountOfInterOP...");
        java.lang.String _getBalanceCostAmountOfInterOP_certkey = "_getBalanceCostAmountOfInterOP_certkey562054594";
        long _getBalanceCostAmountOfInterOP__return = port.getBalanceCostAmountOfInterOP(_getBalanceCostAmountOfInterOP_certkey);
        System.out.println("getBalanceCostAmountOfInterOP.result=" + _getBalanceCostAmountOfInterOP__return);


        }
        {
        System.out.println("Invoking getChargeUnitCost...");
        java.lang.String _getChargeUnitCost_certkey = "_getChargeUnitCost_certkey1377625973";
        java.lang.String _getChargeUnitCost_corpNum = "_getChargeUnitCost_corpNum-1479484154";
        int _getChargeUnitCost_chargeCode = -1501956578;
        int _getChargeUnitCost__return = port.getChargeUnitCost(_getChargeUnitCost_certkey, _getChargeUnitCost_corpNum, _getChargeUnitCost_chargeCode);
        System.out.println("getChargeUnitCost.result=" + _getChargeUnitCost__return);


        }

        System.exit(0);
    }

}
