
package com.baroservice.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-23T08:53:21.169+09:00
 * Generated source version: 3.2.1
 * 
 */
public final class BaroServiceSMSSoap_BaroServiceSMSSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.baroservice.com/", "BaroService_SMS");

    private BaroServiceSMSSoap_BaroServiceSMSSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BaroServiceSMS.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BaroServiceSMS ss = new BaroServiceSMS(wsdlURL, SERVICE_NAME);
        BaroServiceSMSSoap port = ss.getBaroServiceSMSSoap12();  
        
        {
        System.out.println("Invoking getSMSSendMessagesByRefKey...");
        java.lang.String _getSMSSendMessagesByRefKey_certkey = "_getSMSSendMessagesByRefKey_certkey1037800622";
        java.lang.String _getSMSSendMessagesByRefKey_corpNum = "_getSMSSendMessagesByRefKey_corpNum1958045052";
        java.lang.String _getSMSSendMessagesByRefKey_refKey = "_getSMSSendMessagesByRefKey_refKey1827810350";
        com.baroservice.ws.ArrayOfSMSMessage _getSMSSendMessagesByRefKey__return = port.getSMSSendMessagesByRefKey(_getSMSSendMessagesByRefKey_certkey, _getSMSSendMessagesByRefKey_corpNum, _getSMSSendMessagesByRefKey_refKey);
        System.out.println("getSMSSendMessagesByRefKey.result=" + _getSMSSendMessagesByRefKey__return);


        }
        {
        System.out.println("Invoking changeCorpManager...");
        java.lang.String _changeCorpManager_certkey = "_changeCorpManager_certkey-1140310792";
        java.lang.String _changeCorpManager_corpNum = "_changeCorpManager_corpNum-1923738194";
        java.lang.String _changeCorpManager_newManagerID = "_changeCorpManager_newManagerID46354392";
        int _changeCorpManager__return = port.changeCorpManager(_changeCorpManager_certkey, _changeCorpManager_corpNum, _changeCorpManager_newManagerID);
        System.out.println("changeCorpManager.result=" + _changeCorpManager__return);


        }
        {
        System.out.println("Invoking sendMMSMessageFromFTP...");
        java.lang.String _sendMMSMessageFromFTP_certkey = "_sendMMSMessageFromFTP_certkey-390487954";
        java.lang.String _sendMMSMessageFromFTP_corpNum = "_sendMMSMessageFromFTP_corpNum-1964494377";
        java.lang.String _sendMMSMessageFromFTP_senderID = "_sendMMSMessageFromFTP_senderID-1826731441";
        java.lang.String _sendMMSMessageFromFTP_fromNumber = "_sendMMSMessageFromFTP_fromNumber-1912636726";
        java.lang.String _sendMMSMessageFromFTP_toName = "_sendMMSMessageFromFTP_toName-1815124001";
        java.lang.String _sendMMSMessageFromFTP_toNumber = "_sendMMSMessageFromFTP_toNumber-1626670948";
        java.lang.String _sendMMSMessageFromFTP_txtSubject = "_sendMMSMessageFromFTP_txtSubject-859986790";
        java.lang.String _sendMMSMessageFromFTP_txtmessage = "_sendMMSMessageFromFTP_txtmessage-384043999";
        java.lang.String _sendMMSMessageFromFTP_imageFileName = "_sendMMSMessageFromFTP_imageFileName1181030721";
        java.lang.String _sendMMSMessageFromFTP_sendDT = "_sendMMSMessageFromFTP_sendDT-858663784";
        java.lang.String _sendMMSMessageFromFTP_refKey = "_sendMMSMessageFromFTP_refKey-3675019";
        java.lang.String _sendMMSMessageFromFTP__return = port.sendMMSMessageFromFTP(_sendMMSMessageFromFTP_certkey, _sendMMSMessageFromFTP_corpNum, _sendMMSMessageFromFTP_senderID, _sendMMSMessageFromFTP_fromNumber, _sendMMSMessageFromFTP_toName, _sendMMSMessageFromFTP_toNumber, _sendMMSMessageFromFTP_txtSubject, _sendMMSMessageFromFTP_txtmessage, _sendMMSMessageFromFTP_imageFileName, _sendMMSMessageFromFTP_sendDT, _sendMMSMessageFromFTP_refKey);
        System.out.println("sendMMSMessageFromFTP.result=" + _sendMMSMessageFromFTP__return);


        }
        {
        System.out.println("Invoking sendLMSMessage...");
        java.lang.String _sendLMSMessage_certkey = "_sendLMSMessage_certkey12191438";
        java.lang.String _sendLMSMessage_corpNum = "_sendLMSMessage_corpNum1151087097";
        java.lang.String _sendLMSMessage_senderID = "_sendLMSMessage_senderID832137281";
        java.lang.String _sendLMSMessage_fromNumber = "_sendLMSMessage_fromNumber1649481544";
        java.lang.String _sendLMSMessage_toName = "_sendLMSMessage_toName-125541449";
        java.lang.String _sendLMSMessage_toNumber = "_sendLMSMessage_toNumber-1631063972";
        java.lang.String _sendLMSMessage_subject = "_sendLMSMessage_subject-2004042718";
        java.lang.String _sendLMSMessage_contents = "_sendLMSMessage_contents1375106530";
        java.lang.String _sendLMSMessage_sendDT = "_sendLMSMessage_sendDT1602388939";
        java.lang.String _sendLMSMessage_refKey = "_sendLMSMessage_refKey628887085";
        java.lang.String _sendLMSMessage__return = port.sendLMSMessage(_sendLMSMessage_certkey, _sendLMSMessage_corpNum, _sendLMSMessage_senderID, _sendLMSMessage_fromNumber, _sendLMSMessage_toName, _sendLMSMessage_toNumber, _sendLMSMessage_subject, _sendLMSMessage_contents, _sendLMSMessage_sendDT, _sendLMSMessage_refKey);
        System.out.println("sendLMSMessage.result=" + _sendLMSMessage__return);


        }
        {
        System.out.println("Invoking checkCorpIsMember...");
        java.lang.String _checkCorpIsMember_certkey = "_checkCorpIsMember_certkey-1171439341";
        java.lang.String _checkCorpIsMember_corpNum = "_checkCorpIsMember_corpNum-1028498274";
        java.lang.String _checkCorpIsMember_checkCorpNum = "_checkCorpIsMember_checkCorpNum-1032349866";
        int _checkCorpIsMember__return = port.checkCorpIsMember(_checkCorpIsMember_certkey, _checkCorpIsMember_corpNum, _checkCorpIsMember_checkCorpNum);
        System.out.println("checkCorpIsMember.result=" + _checkCorpIsMember__return);


        }
        {
        System.out.println("Invoking cancelReservedSMSMessageByReceiptNum...");
        java.lang.String _cancelReservedSMSMessageByReceiptNum_certkey = "_cancelReservedSMSMessageByReceiptNum_certkey-2140266652";
        java.lang.String _cancelReservedSMSMessageByReceiptNum_corpNum = "_cancelReservedSMSMessageByReceiptNum_corpNum1780236714";
        java.lang.String _cancelReservedSMSMessageByReceiptNum_receiptNum = "_cancelReservedSMSMessageByReceiptNum_receiptNum-931157567";
        int _cancelReservedSMSMessageByReceiptNum__return = port.cancelReservedSMSMessageByReceiptNum(_cancelReservedSMSMessageByReceiptNum_certkey, _cancelReservedSMSMessageByReceiptNum_corpNum, _cancelReservedSMSMessageByReceiptNum_receiptNum);
        System.out.println("cancelReservedSMSMessageByReceiptNum.result=" + _cancelReservedSMSMessageByReceiptNum__return);


        }
        {
        System.out.println("Invoking addUserToCorp...");
        java.lang.String _addUserToCorp_certkey = "_addUserToCorp_certkey-848259434";
        java.lang.String _addUserToCorp_corpNum = "_addUserToCorp_corpNum-1152935631";
        java.lang.String _addUserToCorp_memberName = "_addUserToCorp_memberName-1903855887";
        java.lang.String _addUserToCorp_juminNum = "_addUserToCorp_juminNum-12267994";
        java.lang.String _addUserToCorp_id = "_addUserToCorp_id-473282675";
        java.lang.String _addUserToCorp_pwd = "_addUserToCorp_pwd-1595751105";
        java.lang.String _addUserToCorp_grade = "_addUserToCorp_grade1179759704";
        java.lang.String _addUserToCorp_tel = "_addUserToCorp_tel1641298972";
        java.lang.String _addUserToCorp_hp = "_addUserToCorp_hp20008216";
        java.lang.String _addUserToCorp_email = "_addUserToCorp_email-733141700";
        int _addUserToCorp__return = port.addUserToCorp(_addUserToCorp_certkey, _addUserToCorp_corpNum, _addUserToCorp_memberName, _addUserToCorp_juminNum, _addUserToCorp_id, _addUserToCorp_pwd, _addUserToCorp_grade, _addUserToCorp_tel, _addUserToCorp_hp, _addUserToCorp_email);
        System.out.println("addUserToCorp.result=" + _addUserToCorp__return);


        }
        {
        System.out.println("Invoking sendMessage...");
        java.lang.String _sendMessage_certkey = "_sendMessage_certkey-633086227";
        java.lang.String _sendMessage_corpNum = "_sendMessage_corpNum-984981362";
        java.lang.String _sendMessage_senderID = "_sendMessage_senderID-1817472192";
        java.lang.String _sendMessage_fromNumber = "_sendMessage_fromNumber-745665895";
        java.lang.String _sendMessage_toName = "_sendMessage_toName949068746";
        java.lang.String _sendMessage_toNumber = "_sendMessage_toNumber2012187237";
        java.lang.String _sendMessage_contents = "_sendMessage_contents534490319";
        java.lang.String _sendMessage_sendDT = "_sendMessage_sendDT181954190";
        java.lang.String _sendMessage_refKey = "_sendMessage_refKey497852877";
        java.lang.String _sendMessage__return = port.sendMessage(_sendMessage_certkey, _sendMessage_corpNum, _sendMessage_senderID, _sendMessage_fromNumber, _sendMessage_toName, _sendMessage_toNumber, _sendMessage_contents, _sendMessage_sendDT, _sendMessage_refKey);
        System.out.println("sendMessage.result=" + _sendMessage__return);


        }
        {
        System.out.println("Invoking updateUserInfo...");
        java.lang.String _updateUserInfo_certkey = "_updateUserInfo_certkey-465148887";
        java.lang.String _updateUserInfo_corpNum = "_updateUserInfo_corpNum178517542";
        java.lang.String _updateUserInfo_id = "_updateUserInfo_id867898976";
        java.lang.String _updateUserInfo_memberName = "_updateUserInfo_memberName1191705230";
        java.lang.String _updateUserInfo_juminNum = "_updateUserInfo_juminNum-397024274";
        java.lang.String _updateUserInfo_tel = "_updateUserInfo_tel257462605";
        java.lang.String _updateUserInfo_hp = "_updateUserInfo_hp1263742950";
        java.lang.String _updateUserInfo_email = "_updateUserInfo_email2029092493";
        java.lang.String _updateUserInfo_grade = "_updateUserInfo_grade1221055853";
        int _updateUserInfo__return = port.updateUserInfo(_updateUserInfo_certkey, _updateUserInfo_corpNum, _updateUserInfo_id, _updateUserInfo_memberName, _updateUserInfo_juminNum, _updateUserInfo_tel, _updateUserInfo_hp, _updateUserInfo_email, _updateUserInfo_grade);
        System.out.println("updateUserInfo.result=" + _updateUserInfo__return);


        }
        {
        System.out.println("Invoking getSMSSendMessages...");
        java.lang.String _getSMSSendMessages_certkey = "_getSMSSendMessages_certkey1158451019";
        java.lang.String _getSMSSendMessages_corpNum = "_getSMSSendMessages_corpNum414716489";
        com.baroservice.ws.ArrayOfString _getSMSSendMessages_sendKeyList = new com.baroservice.ws.ArrayOfString();
        java.util.List<java.lang.String> _getSMSSendMessages_sendKeyListString = new java.util.ArrayList<java.lang.String>();
        java.lang.String _getSMSSendMessages_sendKeyListStringVal1 = "_getSMSSendMessages_sendKeyListStringVal1045751979";
        _getSMSSendMessages_sendKeyListString.add(_getSMSSendMessages_sendKeyListStringVal1);
        _getSMSSendMessages_sendKeyList.getString().addAll(_getSMSSendMessages_sendKeyListString);
        com.baroservice.ws.ArrayOfSMSMessage _getSMSSendMessages__return = port.getSMSSendMessages(_getSMSSendMessages_certkey, _getSMSSendMessages_corpNum, _getSMSSendMessages_sendKeyList);
        System.out.println("getSMSSendMessages.result=" + _getSMSSendMessages__return);


        }
        {
        System.out.println("Invoking getSMSSendMessage...");
        java.lang.String _getSMSSendMessage_certkey = "_getSMSSendMessage_certkey627270256";
        java.lang.String _getSMSSendMessage_corpNum = "_getSMSSendMessage_corpNum1098373816";
        java.lang.String _getSMSSendMessage_sendKey = "_getSMSSendMessage_sendKey839991050";
        com.baroservice.ws.SMSMessage _getSMSSendMessage__return = port.getSMSSendMessage(_getSMSSendMessage_certkey, _getSMSSendMessage_corpNum, _getSMSSendMessage_sendKey);
        System.out.println("getSMSSendMessage.result=" + _getSMSSendMessage__return);


        }
        {
        System.out.println("Invoking getLoginURL...");
        java.lang.String _getLoginURL_certkey = "_getLoginURL_certkey1001577691";
        java.lang.String _getLoginURL_corpNum = "_getLoginURL_corpNum452803955";
        java.lang.String _getLoginURL_id = "_getLoginURL_id-642205808";
        java.lang.String _getLoginURL_pwd = "_getLoginURL_pwd-1757266103";
        java.lang.String _getLoginURL__return = port.getLoginURL(_getLoginURL_certkey, _getLoginURL_corpNum, _getLoginURL_id, _getLoginURL_pwd);
        System.out.println("getLoginURL.result=" + _getLoginURL__return);


        }
        {
        System.out.println("Invoking getCertificateRegistDate...");
        java.lang.String _getCertificateRegistDate_certkey = "_getCertificateRegistDate_certkey-855859687";
        java.lang.String _getCertificateRegistDate_corpNum = "_getCertificateRegistDate_corpNum879579784";
        java.lang.String _getCertificateRegistDate__return = port.getCertificateRegistDate(_getCertificateRegistDate_certkey, _getCertificateRegistDate_corpNum);
        System.out.println("getCertificateRegistDate.result=" + _getCertificateRegistDate__return);


        }
        {
        System.out.println("Invoking checkSMSFromNumber...");
        java.lang.String _checkSMSFromNumber_certkey = "_checkSMSFromNumber_certkey1108143177";
        java.lang.String _checkSMSFromNumber_corpNum = "_checkSMSFromNumber_corpNum-988210877";
        java.lang.String _checkSMSFromNumber_fromNumber = "_checkSMSFromNumber_fromNumber-1147097190";
        int _checkSMSFromNumber__return = port.checkSMSFromNumber(_checkSMSFromNumber_certkey, _checkSMSFromNumber_corpNum, _checkSMSFromNumber_fromNumber);
        System.out.println("checkSMSFromNumber.result=" + _checkSMSFromNumber__return);


        }
        {
        System.out.println("Invoking registSMSFromNumber...");
        java.lang.String _registSMSFromNumber_certkey = "_registSMSFromNumber_certkey2058625659";
        java.lang.String _registSMSFromNumber_corpNum = "_registSMSFromNumber_corpNum986441766";
        java.lang.String _registSMSFromNumber_fromNumber = "_registSMSFromNumber_fromNumber-944760292";
        int _registSMSFromNumber__return = port.registSMSFromNumber(_registSMSFromNumber_certkey, _registSMSFromNumber_corpNum, _registSMSFromNumber_fromNumber);
        System.out.println("registSMSFromNumber.result=" + _registSMSFromNumber__return);


        }
        {
        System.out.println("Invoking checkChargeable...");
        java.lang.String _checkChargeable_certkey = "_checkChargeable_certkey-433859260";
        java.lang.String _checkChargeable_corpNum = "_checkChargeable_corpNum-898094027";
        int _checkChargeable_cType = -2085848371;
        int _checkChargeable_docType = -2038695970;
        int _checkChargeable__return = port.checkChargeable(_checkChargeable_certkey, _checkChargeable_corpNum, _checkChargeable_cType, _checkChargeable_docType);
        System.out.println("checkChargeable.result=" + _checkChargeable__return);


        }
        {
        System.out.println("Invoking getSMSSendMessagesByPaging...");
        java.lang.String _getSMSSendMessagesByPaging_certkey = "_getSMSSendMessagesByPaging_certkey677717856";
        java.lang.String _getSMSSendMessagesByPaging_corpNum = "_getSMSSendMessagesByPaging_corpNum614860901";
        java.lang.String _getSMSSendMessagesByPaging_fromDate = "_getSMSSendMessagesByPaging_fromDate-1141509865";
        java.lang.String _getSMSSendMessagesByPaging_toDate = "_getSMSSendMessagesByPaging_toDate-997486655";
        int _getSMSSendMessagesByPaging_countPerPage = 442707341;
        int _getSMSSendMessagesByPaging_currentPage = 1870928732;
        com.baroservice.ws.PagedSMSMessages _getSMSSendMessagesByPaging__return = port.getSMSSendMessagesByPaging(_getSMSSendMessagesByPaging_certkey, _getSMSSendMessagesByPaging_corpNum, _getSMSSendMessagesByPaging_fromDate, _getSMSSendMessagesByPaging_toDate, _getSMSSendMessagesByPaging_countPerPage, _getSMSSendMessagesByPaging_currentPage);
        System.out.println("getSMSSendMessagesByPaging.result=" + _getSMSSendMessagesByPaging__return);


        }
        {
        System.out.println("Invoking ping...");
        port.ping();


        }
        {
        System.out.println("Invoking cancelReservedSMSMessage...");
        java.lang.String _cancelReservedSMSMessage_certkey = "_cancelReservedSMSMessage_certkey-1725657";
        java.lang.String _cancelReservedSMSMessage_corpNum = "_cancelReservedSMSMessage_corpNum470729900";
        java.lang.String _cancelReservedSMSMessage_sendKey = "_cancelReservedSMSMessage_sendKey-297585417";
        int _cancelReservedSMSMessage__return = port.cancelReservedSMSMessage(_cancelReservedSMSMessage_certkey, _cancelReservedSMSMessage_corpNum, _cancelReservedSMSMessage_sendKey);
        System.out.println("cancelReservedSMSMessage.result=" + _cancelReservedSMSMessage__return);


        }
        {
        System.out.println("Invoking getBalanceCostAmount...");
        java.lang.String _getBalanceCostAmount_certkey = "_getBalanceCostAmount_certkey657785144";
        java.lang.String _getBalanceCostAmount_corpNum = "_getBalanceCostAmount_corpNum646938557";
        long _getBalanceCostAmount__return = port.getBalanceCostAmount(_getBalanceCostAmount_certkey, _getBalanceCostAmount_corpNum);
        System.out.println("getBalanceCostAmount.result=" + _getBalanceCostAmount__return);


        }
        {
        System.out.println("Invoking getBaroBillURL...");
        java.lang.String _getBaroBillURL_certkey = "_getBaroBillURL_certkey1502495227";
        java.lang.String _getBaroBillURL_corpNum = "_getBaroBillURL_corpNum-457484855";
        java.lang.String _getBaroBillURL_id = "_getBaroBillURL_id-827189180";
        java.lang.String _getBaroBillURL_pwd = "_getBaroBillURL_pwd1091600588";
        java.lang.String _getBaroBillURL_togo = "_getBaroBillURL_togo-778688894";
        java.lang.String _getBaroBillURL__return = port.getBaroBillURL(_getBaroBillURL_certkey, _getBaroBillURL_corpNum, _getBaroBillURL_id, _getBaroBillURL_pwd, _getBaroBillURL_togo);
        System.out.println("getBaroBillURL.result=" + _getBaroBillURL__return);


        }
        {
        System.out.println("Invoking getMessagesByReceiptNum...");
        java.lang.String _getMessagesByReceiptNum_certkey = "_getMessagesByReceiptNum_certkey1007868895";
        java.lang.String _getMessagesByReceiptNum_corpNum = "_getMessagesByReceiptNum_corpNum-1359360609";
        java.lang.String _getMessagesByReceiptNum_receiptNum = "_getMessagesByReceiptNum_receiptNum2035348809";
        com.baroservice.ws.ArrayOfSMSMessage _getMessagesByReceiptNum__return = port.getMessagesByReceiptNum(_getMessagesByReceiptNum_certkey, _getMessagesByReceiptNum_corpNum, _getMessagesByReceiptNum_receiptNum);
        System.out.println("getMessagesByReceiptNum.result=" + _getMessagesByReceiptNum__return);


        }
        {
        System.out.println("Invoking getErrString...");
        java.lang.String _getErrString_certkey = "_getErrString_certkey-1489904686";
        int _getErrString_errCode = -520878400;
        java.lang.String _getErrString__return = port.getErrString(_getErrString_certkey, _getErrString_errCode);
        System.out.println("getErrString.result=" + _getErrString__return);


        }
        {
        System.out.println("Invoking sendMessages...");
        java.lang.String _sendMessages_certkey = "_sendMessages_certkey532910106";
        java.lang.String _sendMessages_corpNum = "_sendMessages_corpNum1426824261";
        java.lang.String _sendMessages_senderID = "_sendMessages_senderID179805626";
        int _sendMessages_sendCount = 1820677323;
        boolean _sendMessages_cutToSMS = true;
        com.baroservice.ws.ArrayOfXMSMessage _sendMessages_messages = new com.baroservice.ws.ArrayOfXMSMessage();
        java.util.List<com.baroservice.ws.XMSMessage> _sendMessages_messagesXMSMessage = new java.util.ArrayList<com.baroservice.ws.XMSMessage>();
        com.baroservice.ws.XMSMessage _sendMessages_messagesXMSMessageVal1 = new com.baroservice.ws.XMSMessage();
        _sendMessages_messagesXMSMessageVal1.setSenderNum("SenderNum-1365406403");
        _sendMessages_messagesXMSMessageVal1.setReceiverName("ReceiverName-1824098800");
        _sendMessages_messagesXMSMessageVal1.setReceiverNum("ReceiverNum2146422191");
        _sendMessages_messagesXMSMessageVal1.setMessage("Message-457794193");
        _sendMessages_messagesXMSMessageVal1.setRefKey("RefKey-108836432");
        _sendMessages_messagesXMSMessage.add(_sendMessages_messagesXMSMessageVal1);
        _sendMessages_messages.getXMSMessage().addAll(_sendMessages_messagesXMSMessage);
        java.lang.String _sendMessages_sendDT = "_sendMessages_sendDT1380036785";
        java.lang.String _sendMessages__return = port.sendMessages(_sendMessages_certkey, _sendMessages_corpNum, _sendMessages_senderID, _sendMessages_sendCount, _sendMessages_cutToSMS, _sendMessages_messages, _sendMessages_sendDT);
        System.out.println("sendMessages.result=" + _sendMessages__return);


        }
        {
        System.out.println("Invoking checkCERTIsValid...");
        java.lang.String _checkCERTIsValid_certkey = "_checkCERTIsValid_certkey1708851232";
        java.lang.String _checkCERTIsValid_corpNum = "_checkCERTIsValid_corpNum-1862729726";
        int _checkCERTIsValid__return = port.checkCERTIsValid(_checkCERTIsValid_certkey, _checkCERTIsValid_corpNum);
        System.out.println("checkCERTIsValid.result=" + _checkCERTIsValid__return);


        }
        {
        System.out.println("Invoking sendSMSMessage...");
        java.lang.String _sendSMSMessage_certkey = "_sendSMSMessage_certkey161272818";
        java.lang.String _sendSMSMessage_corpNum = "_sendSMSMessage_corpNum-1153365051";
        java.lang.String _sendSMSMessage_senderID = "_sendSMSMessage_senderID364816071";
        java.lang.String _sendSMSMessage_fromNumber = "_sendSMSMessage_fromNumber209768629";
        java.lang.String _sendSMSMessage_toName = "_sendSMSMessage_toName194764608";
        java.lang.String _sendSMSMessage_toNumber = "_sendSMSMessage_toNumber345843783";
        java.lang.String _sendSMSMessage_contents = "_sendSMSMessage_contents2121607289";
        java.lang.String _sendSMSMessage_sendDT = "_sendSMSMessage_sendDT-162310905";
        java.lang.String _sendSMSMessage_refKey = "_sendSMSMessage_refKey2006740243";
        java.lang.String _sendSMSMessage__return = port.sendSMSMessage(_sendSMSMessage_certkey, _sendSMSMessage_corpNum, _sendSMSMessage_senderID, _sendSMSMessage_fromNumber, _sendSMSMessage_toName, _sendSMSMessage_toNumber, _sendSMSMessage_contents, _sendSMSMessage_sendDT, _sendSMSMessage_refKey);
        System.out.println("sendSMSMessage.result=" + _sendSMSMessage__return);


        }
        {
        System.out.println("Invoking getCorpMemberContacts...");
        java.lang.String _getCorpMemberContacts_certkey = "_getCorpMemberContacts_certkey-1053557052";
        java.lang.String _getCorpMemberContacts_corpNum = "_getCorpMemberContacts_corpNum209282987";
        java.lang.String _getCorpMemberContacts_checkCorpNum = "_getCorpMemberContacts_checkCorpNum-366311227";
        com.baroservice.ws.ArrayOfContact _getCorpMemberContacts__return = port.getCorpMemberContacts(_getCorpMemberContacts_certkey, _getCorpMemberContacts_corpNum, _getCorpMemberContacts_checkCorpNum);
        System.out.println("getCorpMemberContacts.result=" + _getCorpMemberContacts__return);


        }
        {
        System.out.println("Invoking getSMSFromNumberURL...");
        java.lang.String _getSMSFromNumberURL_certkey = "_getSMSFromNumberURL_certkey-434541639";
        java.lang.String _getSMSFromNumberURL_corpNum = "_getSMSFromNumberURL_corpNum997809250";
        java.lang.String _getSMSFromNumberURL_id = "_getSMSFromNumberURL_id401446181";
        java.lang.String _getSMSFromNumberURL_pwd = "_getSMSFromNumberURL_pwd-795177809";
        java.lang.String _getSMSFromNumberURL__return = port.getSMSFromNumberURL(_getSMSFromNumberURL_certkey, _getSMSFromNumberURL_corpNum, _getSMSFromNumberURL_id, _getSMSFromNumberURL_pwd);
        System.out.println("getSMSFromNumberURL.result=" + _getSMSFromNumberURL__return);


        }
        {
        System.out.println("Invoking getCertificateExpireDate...");
        java.lang.String _getCertificateExpireDate_certkey = "_getCertificateExpireDate_certkey141830688";
        java.lang.String _getCertificateExpireDate_corpNum = "_getCertificateExpireDate_corpNum950250531";
        java.lang.String _getCertificateExpireDate__return = port.getCertificateExpireDate(_getCertificateExpireDate_certkey, _getCertificateExpireDate_corpNum);
        System.out.println("getCertificateExpireDate.result=" + _getCertificateExpireDate__return);


        }
        {
        System.out.println("Invoking updateUserPWD...");
        java.lang.String _updateUserPWD_certkey = "_updateUserPWD_certkey-1641022986";
        java.lang.String _updateUserPWD_corpNum = "_updateUserPWD_corpNum1439488859";
        java.lang.String _updateUserPWD_id = "_updateUserPWD_id-497109771";
        java.lang.String _updateUserPWD_newPWD = "_updateUserPWD_newPWD-788164501";
        int _updateUserPWD__return = port.updateUserPWD(_updateUserPWD_certkey, _updateUserPWD_corpNum, _updateUserPWD_id, _updateUserPWD_newPWD);
        System.out.println("updateUserPWD.result=" + _updateUserPWD__return);


        }
        {
        System.out.println("Invoking getCashChargeURL...");
        java.lang.String _getCashChargeURL_certkey = "_getCashChargeURL_certkey-308417369";
        java.lang.String _getCashChargeURL_corpNum = "_getCashChargeURL_corpNum1472161882";
        java.lang.String _getCashChargeURL_id = "_getCashChargeURL_id1575383277";
        java.lang.String _getCashChargeURL_pwd = "_getCashChargeURL_pwd749277375";
        java.lang.String _getCashChargeURL__return = port.getCashChargeURL(_getCashChargeURL_certkey, _getCashChargeURL_corpNum, _getCashChargeURL_id, _getCashChargeURL_pwd);
        System.out.println("getCashChargeURL.result=" + _getCashChargeURL__return);


        }
        {
        System.out.println("Invoking getCertificateRegistURL...");
        java.lang.String _getCertificateRegistURL_certkey = "_getCertificateRegistURL_certkey-1217108557";
        java.lang.String _getCertificateRegistURL_corpNum = "_getCertificateRegistURL_corpNum-1154216552";
        java.lang.String _getCertificateRegistURL_id = "_getCertificateRegistURL_id-1579317663";
        java.lang.String _getCertificateRegistURL_pwd = "_getCertificateRegistURL_pwd-1991680049";
        java.lang.String _getCertificateRegistURL__return = port.getCertificateRegistURL(_getCertificateRegistURL_certkey, _getCertificateRegistURL_corpNum, _getCertificateRegistURL_id, _getCertificateRegistURL_pwd);
        System.out.println("getCertificateRegistURL.result=" + _getCertificateRegistURL__return);


        }
        {
        System.out.println("Invoking updateCorpInfo...");
        java.lang.String _updateCorpInfo_certkey = "_updateCorpInfo_certkey113305397";
        java.lang.String _updateCorpInfo_corpNum = "_updateCorpInfo_corpNum-1302402296";
        java.lang.String _updateCorpInfo_corpName = "_updateCorpInfo_corpName926347808";
        java.lang.String _updateCorpInfo_ceoName = "_updateCorpInfo_ceoName890535349";
        java.lang.String _updateCorpInfo_bizType = "_updateCorpInfo_bizType-1957909533";
        java.lang.String _updateCorpInfo_bizClass = "_updateCorpInfo_bizClass-802644864";
        java.lang.String _updateCorpInfo_postNum = "_updateCorpInfo_postNum517099392";
        java.lang.String _updateCorpInfo_addr1 = "_updateCorpInfo_addr1-1871824257";
        java.lang.String _updateCorpInfo_addr2 = "_updateCorpInfo_addr21469534522";
        int _updateCorpInfo__return = port.updateCorpInfo(_updateCorpInfo_certkey, _updateCorpInfo_corpNum, _updateCorpInfo_corpName, _updateCorpInfo_ceoName, _updateCorpInfo_bizType, _updateCorpInfo_bizClass, _updateCorpInfo_postNum, _updateCorpInfo_addr1, _updateCorpInfo_addr2);
        System.out.println("updateCorpInfo.result=" + _updateCorpInfo__return);


        }
        {
        System.out.println("Invoking registCorp...");
        java.lang.String _registCorp_certkey = "_registCorp_certkey549677537";
        java.lang.String _registCorp_corpNum = "_registCorp_corpNum-344870986";
        java.lang.String _registCorp_corpName = "_registCorp_corpName1417829610";
        java.lang.String _registCorp_ceoName = "_registCorp_ceoName-258641669";
        java.lang.String _registCorp_bizType = "_registCorp_bizType715183482";
        java.lang.String _registCorp_bizClass = "_registCorp_bizClass-1000009113";
        java.lang.String _registCorp_postNum = "_registCorp_postNum1158410608";
        java.lang.String _registCorp_addr1 = "_registCorp_addr11614470613";
        java.lang.String _registCorp_addr2 = "_registCorp_addr2331820205";
        java.lang.String _registCorp_memberName = "_registCorp_memberName-1172548738";
        java.lang.String _registCorp_juminNum = "_registCorp_juminNum1704199557";
        java.lang.String _registCorp_id = "_registCorp_id-669026461";
        java.lang.String _registCorp_pwd = "_registCorp_pwd-178454829";
        java.lang.String _registCorp_grade = "_registCorp_grade-141974977";
        java.lang.String _registCorp_tel = "_registCorp_tel-1781902564";
        java.lang.String _registCorp_hp = "_registCorp_hp-2096576168";
        java.lang.String _registCorp_email = "_registCorp_email-1808097700";
        int _registCorp__return = port.registCorp(_registCorp_certkey, _registCorp_corpNum, _registCorp_corpName, _registCorp_ceoName, _registCorp_bizType, _registCorp_bizClass, _registCorp_postNum, _registCorp_addr1, _registCorp_addr2, _registCorp_memberName, _registCorp_juminNum, _registCorp_id, _registCorp_pwd, _registCorp_grade, _registCorp_tel, _registCorp_hp, _registCorp_email);
        System.out.println("registCorp.result=" + _registCorp__return);


        }
        {
        System.out.println("Invoking getSMSHistoryURL...");
        java.lang.String _getSMSHistoryURL_certkey = "_getSMSHistoryURL_certkey1464587676";
        java.lang.String _getSMSHistoryURL_corpNum = "_getSMSHistoryURL_corpNum-1312907152";
        java.lang.String _getSMSHistoryURL_id = "_getSMSHistoryURL_id168946168";
        java.lang.String _getSMSHistoryURL_pwd = "_getSMSHistoryURL_pwd-1884286917";
        java.lang.String _getSMSHistoryURL__return = port.getSMSHistoryURL(_getSMSHistoryURL_certkey, _getSMSHistoryURL_corpNum, _getSMSHistoryURL_id, _getSMSHistoryURL_pwd);
        System.out.println("getSMSHistoryURL.result=" + _getSMSHistoryURL__return);


        }
        {
        System.out.println("Invoking sendMMSMessage...");
        java.lang.String _sendMMSMessage_certkey = "_sendMMSMessage_certkey-1959185977";
        java.lang.String _sendMMSMessage_corpNum = "_sendMMSMessage_corpNum-1846945792";
        java.lang.String _sendMMSMessage_senderID = "_sendMMSMessage_senderID1607355337";
        java.lang.String _sendMMSMessage_fromNumber = "_sendMMSMessage_fromNumber-1850733184";
        java.lang.String _sendMMSMessage_toName = "_sendMMSMessage_toName-44535032";
        java.lang.String _sendMMSMessage_toNumber = "_sendMMSMessage_toNumber1751260378";
        java.lang.String _sendMMSMessage_txtSubject = "_sendMMSMessage_txtSubject-530876790";
        java.lang.String _sendMMSMessage_txtmessage = "_sendMMSMessage_txtmessage-76088506";
        byte[] _sendMMSMessage_imageFile = new byte[] {};
        java.lang.String _sendMMSMessage_sendDT = "_sendMMSMessage_sendDT-1814089264";
        java.lang.String _sendMMSMessage_refKey = "_sendMMSMessage_refKey1552244508";
        java.lang.String _sendMMSMessage__return = port.sendMMSMessage(_sendMMSMessage_certkey, _sendMMSMessage_corpNum, _sendMMSMessage_senderID, _sendMMSMessage_fromNumber, _sendMMSMessage_toName, _sendMMSMessage_toNumber, _sendMMSMessage_txtSubject, _sendMMSMessage_txtmessage, _sendMMSMessage_imageFile, _sendMMSMessage_sendDT, _sendMMSMessage_refKey);
        System.out.println("sendMMSMessage.result=" + _sendMMSMessage__return);


        }
        {
        System.out.println("Invoking getSMSSendState...");
        java.lang.String _getSMSSendState_certkey = "_getSMSSendState_certkey1008786276";
        java.lang.String _getSMSSendState_corpNum = "_getSMSSendState_corpNum-372310834";
        java.lang.String _getSMSSendState_sendKey = "_getSMSSendState_sendKey-1683360755";
        int _getSMSSendState__return = port.getSMSSendState(_getSMSSendState_certkey, _getSMSSendState_corpNum, _getSMSSendState_sendKey);
        System.out.println("getSMSSendState.result=" + _getSMSSendState__return);


        }
        {
        System.out.println("Invoking getBalanceCostAmountOfInterOP...");
        java.lang.String _getBalanceCostAmountOfInterOP_certkey = "_getBalanceCostAmountOfInterOP_certkey286930103";
        long _getBalanceCostAmountOfInterOP__return = port.getBalanceCostAmountOfInterOP(_getBalanceCostAmountOfInterOP_certkey);
        System.out.println("getBalanceCostAmountOfInterOP.result=" + _getBalanceCostAmountOfInterOP__return);


        }
        {
        System.out.println("Invoking getChargeUnitCost...");
        java.lang.String _getChargeUnitCost_certkey = "_getChargeUnitCost_certkey-482592673";
        java.lang.String _getChargeUnitCost_corpNum = "_getChargeUnitCost_corpNum-1702853652";
        int _getChargeUnitCost_chargeCode = -283934785;
        int _getChargeUnitCost__return = port.getChargeUnitCost(_getChargeUnitCost_certkey, _getChargeUnitCost_corpNum, _getChargeUnitCost_chargeCode);
        System.out.println("getChargeUnitCost.result=" + _getChargeUnitCost__return);


        }

        System.exit(0);
    }

}
